<a href="https://colab.research.google.com/github/yuyangweng/NLP/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count=CountVectorizer()
docs=np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])

bag=count.fit_transform(docs)
print(bag.shape)
print()
print(count.vocabulary_)
print()
print(bag.toarray())
# print()
# print(bag)


(3, 9)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
docs=np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])
tokenizer = Tokenizer(num_words = 100)
Doc=tokenizer.fit_on_texts(docs)
word_index = tokenizer.word_index
print(word_index)



{'is': 1, 'the': 2, 'sun': 3, 'shining': 4, 'weather': 5, 'sweet': 6, 'and': 7, 'one': 8, 'two': 9}


In [3]:
import tensorflow as tf
example_strings = docs=np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])

VOCAB_SIZE = 10
tk = tf.keras.preprocessing.text.Tokenizer(num_words=VOCAB_SIZE)
tk.fit_on_texts(example_strings)

tk.sequences_to_matrix(tk.texts_to_sequences(example_strings), mode='tfidf')

array([[0.        , 0.55961579, 0.55961579, 0.69314718, 0.69314718,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.55961579, 0.55961579, 0.        , 0.        ,
        0.69314718, 0.69314718, 0.        , 0.        , 0.        ],
       [0.        , 1.17441657, 0.94751189, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 1.55141507, 1.55141507, 0.91629073]])

In [4]:
np.set_printoptions(precision=2)

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer(use_idf=True,norm='l2',smooth_idf=True)
bag=count.fit_transform(docs)
print(tfidf.fit_transform(bag).toarray())
print()
print(tfidf.fit_transform(bag))

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]

  (0, 6)	0.4337078595086741
  (0, 4)	0.5584778353707552
  (0, 3)	0.5584778353707552
  (0, 1)	0.4337078595086741
  (1, 8)	0.5584778353707552
  (1, 6)	0.4337078595086741
  (1, 5)	0.5584778353707552
  (1, 1)	0.4337078595086741
  (2, 8)	0.191038921512224
  (2, 7)	0.25119322405394995
  (2, 6)	0.296717529270996
  (2, 5)	0.191038921512224
  (2, 4)	0.191038921512224
  (2, 3)	0.191038921512224
  (2, 2)	0.5023864481078999
  (2, 1)	0.44507629390649395
  (2, 0)	0.5023864481078999


In [6]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf=TfidfTransformer(use_idf=True,norm=None,smooth_idf=True)
bag=count.fit_transform(docs)
print(tfidf.fit_transform(bag).toarray())
print()
print(tfidf.fit_transform(bag))
print(tfidf.fit_transform(bag).toarray().shape[0])

[[0.   1.   0.   1.29 1.29 0.   1.   0.   0.  ]
 [0.   1.   0.   0.   0.   1.29 1.   0.   1.29]
 [3.39 3.   3.39 1.29 1.29 1.29 2.   1.69 1.29]]

  (0, 6)	1.0
  (0, 4)	1.2876820724517808
  (0, 3)	1.2876820724517808
  (0, 1)	1.0
  (1, 8)	1.2876820724517808
  (1, 6)	1.0
  (1, 5)	1.2876820724517808
  (1, 1)	1.0
  (2, 8)	1.2876820724517808
  (2, 7)	1.6931471805599454
  (2, 6)	2.0
  (2, 5)	1.2876820724517808
  (2, 4)	1.2876820724517808
  (2, 3)	1.2876820724517808
  (2, 2)	3.386294361119891
  (2, 1)	3.0
  (2, 0)	3.386294361119891
3


In [7]:
l2_tfidf=[]
for row in range(tfidf.fit_transform(bag).toarray().shape[0]):
  row_tfidf=tfidf.fit_transform(bag).toarray()[row]
  l2_tfidf.append(row_tfidf/np.sqrt(np.sum(row_tfidf**2)))
l2_tfidf=np.array(l2_tfidf)
print(l2_tfidf)

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


In [8]:
from nltk.stem.porter import PorterStemmer

porter=PorterStemmer()

def tokenizer(text):
  return text.split()
def tokenizer_porter(text):
  return [porter.stem(word) for word in text.split()]

In [9]:
print(tokenizer('runners like running and thus they run'))
print(tokenizer_porter('runners like running and thus they run'))

['runners', 'like', 'running', 'and', 'thus', 'they', 'run']
['runner', 'like', 'run', 'and', 'thu', 'they', 'run']


In [10]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop=stopwords.words('english')
[w for w in tokenizer_porter('a runners like running and thus they run a lot') if w not in stop]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['runner', 'like', 'run', 'thu', 'run', 'lot']

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words=stop, tokenizer=tokenizer_porter)
Docs = tfidf.fit_transform(docs).toarray()
Docs

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'ani', 'becaus', 'befor', 'doe', 'dure', 'ha', 'hi', "it'", 'onc', 'onli', 'ourselv', "she'", "should'v", 'themselv', 'thi', 'veri', 'wa', 'whi', "you'r", "you'v", 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


array([[0.  , 0.8 , 0.  , 0.61, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.8 , 0.  , 0.  , 0.61],
       [0.7 , 0.  , 0.35, 0.27, 0.  , 0.35, 0.35, 0.27]])

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [13]:
# load in all the modules we're going to need
import nltk, re, string, collections
from nltk.util import ngrams # function for making ngrams

# this corpus is pretty big, so let's look at just one of the files in it
with open("/content/drive/MyDrive/00NLP/text8", "r") as file:
    text = file.read()[0:10000] # str

# check to make sure the file read in alright; let's print out the first 100 characters
text[0:100]

' anarchism originated as a term of abuse first used against early working class radicals including t'

In [19]:
tokenized=text.split()
Bigrams = ngrams(tokenized, 2)
bigramsFreq=collections.Counter(Bigrams)
bigramsFreq

Counter({('anarchism', 'originated'): 1,
         ('originated', 'as'): 1,
         ('as', 'a'): 5,
         ('a', 'term'): 1,
         ('term', 'of'): 1,
         ('of', 'abuse'): 1,
         ('abuse', 'first'): 1,
         ('first', 'used'): 1,
         ('used', 'against'): 1,
         ('against', 'early'): 1,
         ('early', 'working'): 1,
         ('working', 'class'): 2,
         ('class', 'radicals'): 1,
         ('radicals', 'including'): 1,
         ('including', 'the'): 3,
         ('the', 'diggers'): 2,
         ('diggers', 'of'): 1,
         ('of', 'the'): 11,
         ('the', 'english'): 3,
         ('english', 'revolution'): 1,
         ('revolution', 'and'): 1,
         ('and', 'the'): 3,
         ('the', 'sans'): 1,
         ('sans', 'culottes'): 1,
         ('culottes', 'of'): 1,
         ('the', 'french'): 3,
         ('french', 'revolution'): 3,
         ('revolution', 'whilst'): 1,
         ('whilst', 'the'): 1,
         ('the', 'term'): 4,
         ('term', 'is')

In [20]:
bigramsFreq.most_common(20)

[(('one', 'eight'), 12),
 (('of', 'the'), 11),
 (('in', 'the'), 10),
 (('the', 'first'), 9),
 (('in', 'one'), 7),
 (('in', 'a'), 6),
 (('as', 'the'), 6),
 (('as', 'a'), 5),
 (('the', 'term'), 4),
 (('from', 'the'), 4),
 (('it', 'is'), 4),
 (('to', 'be'), 4),
 (('that', 'the'), 4),
 (('proudhon', 's'), 4),
 (('s', 'ideas'), 4),
 (('including', 'the'), 3),
 (('the', 'english'), 3),
 (('and', 'the'), 3),
 (('the', 'french'), 3),
 (('french', 'revolution'), 3)]